In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns',None)

In [29]:
balls = pd.read_csv('deliveries_updated_ipl_upto_2025.csv')

In [30]:
balls.head()

,matchId,inning,over_ball,over,ball,batting_team,bowling_team,batsman,non_striker,bowler,batsman_runs,extras,isWide,isNoBall,Byes,LegByes,Penalty,dismissal_kind,player_dismissed,date
0,335982,1,0.1,0,1,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,BB McCullum,P Kumar,0,1,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2008-04-18
1,335982,1,0.2,0,2,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-04-18
2,335982,1,0.3,0,3,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2008-04-18
3,335982,1,0.4,0,4,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-04-18
4,335982,1,0.5,0,5,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-04-18

In [31]:
balls['date'] = pd.to_datetime(balls['date'])

In [32]:
balls['isWide'] = balls['isWide'].fillna(0.0)
balls['isNoBall'] = balls['isNoBall'].fillna(0.0)
balls['player_dismissed'] = balls['player_dismissed'].fillna(0.0)
balls.head()

,matchId,inning,over_ball,over,ball,batting_team,bowling_team,batsman,non_striker,bowler,batsman_runs,extras,isWide,isNoBall,Byes,LegByes,Penalty,dismissal_kind,player_dismissed,date
0,335982,1,0.1,0,1,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,BB McCullum,P Kumar,0,1,0.0,0.0,NaN,1.0,NaN,NaN,0.0,2008-04-18
1,335982,1,0.2,0,2,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,2008-04-18
2,335982,1,0.3,0,3,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,1,1.0,0.0,NaN,NaN,NaN,NaN,0.0,2008-04-18
3,335982,1,0.4,0,4,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,2008-04-18
4,335982,1,0.5,0,5,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,2008-04-18

In [33]:
balls['Byes'] = balls['Byes'].fillna(0)
balls['LegByes'] = balls['LegByes'].fillna(0)
balls['Penalty'] = balls['Penalty'].fillna(0)

balls['batsman_runs'] = balls['batsman_runs'] + balls['Byes'] + balls['LegByes']

In [34]:
balls.drop(
    ['Byes','LegByes','over_ball','dismissal_kind','extras'],
    axis=1,
    inplace=True,
    errors='ignore'
)

In [35]:
balls.head()

,matchId,inning,over,ball,batting_team,bowling_team,batsman,non_striker,bowler,batsman_runs,isWide,isNoBall,Penalty,player_dismissed,date
0,335982,1,0,1,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,BB McCullum,P Kumar,1.0,0.0,0.0,0.0,0.0,2008-04-18
1,335982,1,0,2,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0.0,0.0,0.0,0.0,0.0,2008-04-18
2,335982,1,0,3,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0.0,1.0,0.0,0.0,0.0,2008-04-18
3,335982,1,0,4,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0.0,0.0,0.0,0.0,0.0,2008-04-18
4,335982,1,0,5,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0.0,0.0,0.0,0.0,0.0,2008-04-18

In [36]:
balls['isWide'] = balls['isWide'] + balls['Penalty']
balls.drop(columns=['Penalty'], inplace=True)
balls.columns

Index(['matchId', 'inning', 'over', 'ball', 'batting_team', 'bowling_team',
       'batsman', 'non_striker', 'bowler', 'batsman_runs', 'isWide',
       'isNoBall', 'player_dismissed', 'date'],
      dtype='object')

In [38]:
balls.head()

,matchId,inning,over,ball,batting_team,bowling_team,batsman,non_striker,bowler,batsman_runs,isWide,isNoBall,player_dismissed,date
0,335982,1,0,1,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,BB McCullum,P Kumar,1.0,0.0,0.0,0.0,2008-04-18
1,335982,1,0,2,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0.0,0.0,0.0,0.0,2008-04-18
2,335982,1,0,3,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0.0,1.0,0.0,0.0,2008-04-18
3,335982,1,0,4,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0.0,0.0,0.0,0.0,2008-04-18
4,335982,1,0,5,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0.0,0.0,0.0,0.0,2008-04-18

In [40]:
balls['inning'].unique()

array([1, 2, 3, 4, 5, 6])

In [41]:
balls = balls[balls['inning'].isin([1, 2])].copy()
balls['inning'] = balls['inning'].map({1: 0, 2: 1})

In [42]:
print(balls.shape)
print(" -------------------- ")
print(balls.isnull().sum())
print(" -------------------- ")
print(balls.info())

(278034, 14)
 --------------------
matchId             0
inning              0
over                0
ball                0
batting_team        0
bowling_team        0
batsman             0
non_striker         0
bowler              0
batsman_runs        0
isWide              0
isNoBall            0
player_dismissed    0
date                0
dtype: int64
 --------------------
<class 'pandas.core.frame.DataFrame'>
Index: 278034 entries, 0 to 278204
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   matchId           278034 non-null  int64
 1   inning            278034 non-null  int64
 2   over              278034 non-null  int64
 3   ball              278034 non-null  int64
 4   batting_team      278034 non-null  object
 5   bowling_team      278034 non-null  object
 6   batsman           278034 non-null  object
 7   non_striker       278034 non-null  object
 8   bowler            278034 non-null  object
 9   batsman_runs      278034 non-null  float64
 10  isWide            278034 non-null  float64
 11  isNoBall          278034 non-null  float64
 12  player_dismissed  278034 non-null  object
 13  date              278034 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int64(4), object(6)
memory usage: 31.8+ MB
None

In [43]:
balls.to_csv('cleaned_deliveries_till_2025.csv')