In [1]:
import pandas as pd
import numpy as np

In [3]:
deliveries = pd.read_parquet("../ml-service/data/processed/v3_alpha/clean_deliveries.parquet")
matches = pd.read_parquet("../ml-service/data/processed/v3_alpha/clean_matches.parquet")

In [4]:
deliveries.head()

,matchId,inning,over,ball,batting_team,bowling_team,batsman,non_striker,bowler,batsman_runs,isWide,isNoBall,player_dismissed,date
0,335982,0,0,1,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,BB McCullum,P Kumar,1,0,0,0,2008-04-18
1,335982,0,0,2,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,0,0,2008-04-18
2,335982,0,0,3,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,1,0,0,2008-04-18
3,335982,0,0,4,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,0,0,2008-04-18
4,335982,0,0,5,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,0,0,2008-04-18

In [5]:
matches.head()

,season,venue,winner_runs,date,winner,team1,team2,winner_wickets,player_of_match,matchId
0,2008,M Chinnaswamy Stadium,140,2008-04-18,Kolkata Knight Riders,Royal Challengers Bangalore,Kolkata Knight Riders,0,BB McCullum,335982
1,2008,"Punjab Cricket Association Stadium, Mohali",33,2008-04-19,Chennai Super Kings,Kings XI Punjab,Chennai Super Kings,0,MEK Hussey,335983
2,2008,Feroz Shah Kotla,0,2008-04-19,Delhi Daredevils,Delhi Daredevils,Rajasthan Royals,9,MF Maharoof,335984
3,2008,Eden Gardens,0,2008-04-20,Kolkata Knight Riders,Kolkata Knight Riders,Deccan Chargers,5,DJ Hussey,335986
4,2008,Wankhede Stadium,0,2008-04-20,Royal Challengers Bangalore,Mumbai Indians,Royal Challengers Bangalore,5,MV Boucher,335985

In [13]:
batsmen = set(deliveries['batsman'].unique())
non_strikers = set(deliveries['non_striker'].unique())

common_players = batsmen & non_strikers

len(common_players)

689

In [ ]:
batsmen - non_strikers

{'C Nanda',
 'IC Pandey',
 'JL Denly',
 'KM Asif',
 'KR Sen',
 'KT Maphaka',
 'MS Bhandage',
 'Musheer Khan',
 'R Sanjay Yadav',
 'RJ Gleeson',
 'S Lamichhane',
 'Shivam Sharma',
 'U Kaul',
 'V Pratap Singh',
 'VS Yeligati'}

In [15]:
non_strikers - batsmen

{'A Nel', 'BW Hilfenhaus', 'C Ganapathy', 'TP Sudhindra'}

In [16]:
import json

players = set(deliveries['batsman'].unique()) | set(deliveries['non_striker'].unique())

players_list = sorted(list(players))

with open('players.json', 'w') as f:
    json.dump(players_list, f, indent=4)

In [17]:
matches['venue'].unique()

array(['M Chinnaswamy Stadium',
       'Punjab Cricket Association Stadium, Mohali', 'Feroz Shah Kotla',
       'Eden Gardens', 'Wankhede Stadium', 'Sawai Mansingh Stadium',
       'Rajiv Gandhi International Stadium, Uppal',
       'MA Chidambaram Stadium, Chepauk', 'Dr DY Patil Sports Academy',
       'Newlands', "St George's Park", 'Kingsmead', 'SuperSport Park',
       'Buffalo Park', 'New Wanderers Stadium', 'De Beers Diamond Oval',
       'OUTsurance Oval', 'Brabourne Stadium',
       'Sardar Patel Stadium, Motera', 'Barabati Stadium',
       'Brabourne Stadium, Mumbai',
       'Vidarbha Cricket Association Stadium, Jamtha',
       'Himachal Pradesh Cricket Association Stadium', 'Nehru Stadium',
       'Holkar Cricket Stadium',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'Subrata Roy Sahara Stadium',
       'Maharashtra Cricket Association Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'JSCA International Stadium Complex', 'Sheikh Zayed Stadium',
       'Sharjah Cricket Stadium', 'Dubai International Cricket Stadium',
       'Punjab Cricket Association IS Bindra Stadium, Mohali',
       'Saurashtra Cricket Association Stadium', 'Green Park',
       'M.Chinnaswamy Stadium',
       'Punjab Cricket Association IS Bindra Stadium',
       'Rajiv Gandhi International Stadium', 'MA Chidambaram Stadium',
       'Arun Jaitley Stadium', 'MA Chidambaram Stadium, Chepauk, Chennai',
       'Wankhede Stadium, Mumbai', 'Narendra Modi Stadium, Ahmedabad',
       'Arun Jaitley Stadium, Delhi', 'Zayed Cricket Stadium, Abu Dhabi',
       'Dr DY Patil Sports Academy, Mumbai',
       'Maharashtra Cricket Association Stadium, Pune',
       'Eden Gardens, Kolkata',
       'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh',
       'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow',
       'Rajiv Gandhi International Stadium, Uppal, Hyderabad',
       'M Chinnaswamy Stadium, Bengaluru',
       'Barsapara Cricket Stadium, Guwahati',
       'Sawai Mansingh Stadium, Jaipur',
       'Himachal Pradesh Cricket Association Stadium, Dharamsala',
       'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam',
       'Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh'],
      dtype=object)

In [19]:
import json

venues = sorted(matches['venue'].unique())

with open('venues.json', 'w') as f:
    json.dump(venues, f, indent=4)