In [48]:
import pandas as pd
import numpy as np

In [49]:
balls = pd.read_csv('./data3.csv',index_col='Unnamed: 0')

In [50]:
balls.columns

Index(['matchId', 'inning', 'over', 'batsman_runs', 'isWide', 'isNoBall',
       'total_runs', 'batsman', 'non_striker', 'bowler', 'player_dismissed',
       'balls_remaining', 'phase', 'current_score', 'wickets_fallen', 'target',
       'last_over_runs', 'total_balls_in_over', 'balls_since_boundary',
       'percentage_target_achieved', 'venue', 'current_run_rate',
       'required_run_rate', 'season', 'sin_ball', 'cos_ball'],
      dtype='object')

In [51]:
balls[balls.duplicated()]

Empty DataFrame
Columns: [matchId, inning, over, batsman_runs, isWide, isNoBall, total_runs, batsman, non_striker, bowler, player_dismissed, balls_remaining, phase, current_score, wickets_fallen, target, last_over_runs, total_balls_in_over, balls_since_boundary, percentage_target_achieved, venue, current_run_rate, required_run_rate, season, sin_ball, cos_ball]
Index: []

In [52]:
balls['inning'].unique()

array([0, 1])

In [53]:
(balls['over']*20).unique()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [54]:
(balls['batsman_runs']*6).unique()

array([1., 0., 4., 6., 2., 5., 3.])

In [55]:
balls['isWide'].unique()

array([0, 1])

In [56]:
balls.dtypes

matchId                         int64
inning                          int64
over                          float64
batsman_runs                  float64
isWide                          int64
isNoBall                        int64
total_runs                    float64
batsman                        object
non_striker                    object
bowler                         object
player_dismissed               object
balls_remaining               float64
phase                           int64
current_score                 float64
wickets_fallen                float64
target                        float64
last_over_runs                float64
total_balls_in_over           float64
balls_since_boundary          float64
percentage_target_achieved    float64
venue                          object
current_run_rate              float64
required_run_rate             float64
season                        float64
sin_ball                      float64
cos_ball                      float64
dtype: object

In [57]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)
pd.set_option('display.float_format', '{:.6f}'.format)

In [58]:
balls.describe()

,matchId,inning,over,batsman_runs,isWide,isNoBall,total_runs,balls_remaining,phase,current_score,wickets_fallen,target,last_over_runs,total_balls_in_over,balls_since_boundary,percentage_target_achieved,current_run_rate,required_run_rate,season,sin_ball,cos_ball
count,278989.000000,278989.000000,278989.000000,278989.000000,278989.000000,278989.000000,278989.000000,278989.000000,278989.000000,278989.000000,278989.000000,278989.000000,278989.000000,278989.000000,278989.000000,278989.000000,278989.000000,278989.000000,278989.000000,278989.000000,278989.000000
mean,941316.583786,0.482886,0.459713,0.215557,0.038912,0.004129,0.037122,0.511630,0.913488,0.385577,0.245943,0.411049,0.039000,0.366354,0.045603,0.214984,0.212912,0.139278,0.037905,0.009350,-0.004889
std,381852.086187,0.499708,0.284047,0.274146,0.193385,0.064126,0.045202,0.284272,0.730700,0.249737,0.210159,0.439271,0.024168,0.187288,0.055873,0.293272,0.067865,0.206334,1.011735,0.711461,0.702649
min,335982.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.100000,0.000000,0.000000,0.000000,0.000000,-1.638356,-0.866025,-1.000000
25%,548352.000000,0.000000,0.200000,0.000000,0.000000,0.000000,0.000000,0.266667,0.000000,0.180000,0.100000,0.000000,0.020000,0.200000,0.008333,0.000000,0.177536,0.000000,-0.867365,-0.866025,-0.500000
50%,1082600.000000,0.000000,0.450000,0.166667,0.000000,0.000000,0.027778,0.516667,1.000000,0.365000,0.200000,0.000000,0.035000,0.400000,0.025000,0.000000,0.212766,0.000000,0.096374,0.000000,-0.500000
75%,1304048.000000,1.000000,0.700000,0.166667,0.000000,0.000000,0.027778,0.758333,1.000000,0.565000,0.400000,0.840000,0.055000,0.500000,0.058333,0.417040,0.248148,0.248148,1.060113,0.866025,0.500000
max,1485779.000000,1.000000,0.950000,1.000000,1.000000,1.000000,0.194444,1.000000,2.000000,1.435000,1.000000,1.440000,0.185000,1.700000,0.833333,1.166667,1.833333,2.000000,1.638356,0.866025,1.000000

In [59]:
matches = pd.read_csv('./matches_updated_ipl_upto_2025.csv')

In [60]:
matches.columns

Index(['season', 'venue', 'event', 'winner_runs', 'umpire2', 'toss_winner',
       'date', 'neutralvenue', 'umpire1', 'city', 'reserve_umpire', 'winner',
       'eliminator', 'date1', 'method', 'team1', 'toss_decision', 'gender',
       'team2', 'balls_per_over', 'winner_wickets', 'tv_umpire',
       'player_of_match', 'match_referee', 'outcome', 'date2', 'match_number',
       'matchId'],
      dtype='object')

In [61]:
matches['method'] = matches['method'].fillna("No Rain")

In [62]:
matches['method'].unique()

array(['No Rain', 'D/L'], dtype=object)

In [70]:
matches[(matches['winner'].isna())&(matches['method']=='D/L')]

Empty DataFrame
Columns: [season, venue, event, winner_runs, umpire2, toss_winner, date, neutralvenue, umpire1, city, reserve_umpire, winner, eliminator, date1, method, team1, toss_decision, gender, team2, balls_per_over, winner_wickets, tv_umpire, player_of_match, match_referee, outcome, date2, match_number, matchId]
Index: []